print(20*'-')
print('Faça Sua Inscrição')
print(20*'-')
print('Muito prazer! Somos Do Curso De Progamação De Python')
nome = input('Qual é o seu nome?')
email = input('Qual seu email?')
escola = input('Qual o nome da sua escola?')
print(20*'-')
print('Cadastro Realizado Com Sucesso! ')
print(20*'-')
print(f'Usuario(a): {nome}')
print(f'email: {email} ')
print(f'escola:{escola} ')